name: CI-CD

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Docker Login
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USER}}
          password: ${{ secrets.DOCKERHUB_PWD}}
      - name: Docker build and push
        uses: docker/build-push-action@v2.7.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            jvbravoo/rotten-potatoes:latest
            jvbravoo/rotten-potatoes:v1
            
  CD:
    needs: [CI]
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Kubernets set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secret.K8S_CONFIG }}
          
      - name: Deploy to kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          images: jvbravoo/rotten-potatoes:v1
          manifests: |
            deployment.yaml
